### ISSUE TITLE
Missing UNIX domain sockets example

### ISSUE THREAD

**Issue by troglobit** [troydhanson/misc#1]
Hi Troy!

Just found your excellent tutorial on UNIX domain sockets online, http://troydhanson.github.io/misc/Unix_domain_sockets.html, but the examples are not available in the referenced repo (this). 

Maybe you forgot to add them, or have moved them elsewhere?

Cheers
 /Joachim

**Comment by troglobit** [comment]
Ah, now I see!  They've moved, http://troydhanson.github.io/network/Unix_domain_sockets.html, or I just stumbled on a dead link.  Sorry for the noise :)

**Comment by troydhanson** [comment]
Hi Joachim - glad you found the new URL. I wish I'd left them at the original URL since I realized too late there are probably other links to that document in various places that I've now broken. Lesson learned. :)

**Comment by troglobit** [comment]
No worries :smiley: :+1:
